version: "5"
services:
  service-task-home:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
  springdockercompose:
    image: springdockercompose:latest
    container_name: "springdockercompose"
    ports:
      - 9090:8080
    links:
      - service-task-home